server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user_route
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: grievance_route
          uri: lb://grievance-service
          predicates:
            - Path=/grievances/**
        - id: bookmark_route
          uri: lb://bookmark-service
          predicates:
            - Path=/bookmarks/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/