server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/grievance_user_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: Pavitra@22
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true